# Generated by Django 5.1.1 on 2025-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunit',
            name='size',
            field=models.CharField(choices=[('small', 'Маленький (до 1 м3)'), ('medium', 'Средний (1-5 м3)'), ('large', 'Большой (Более 5 м3)')], max_length=10),
        ),
    ]
